### ISSUE TITLE
pkl模型如何使用

### ISSUE THREAD

**Issue by hotea1** [kourenke/LW-IRSTNet#2]
大佬好，请问您的项目中如何加载pkl文件并用于检测呢？这个文件是同时包含网络模型结构和模型参数吗？

**Comment by kourenke** [comment]
pkl文件仅包含模型参数，需要把网络模型放到同一路径

**Comment by hotea1** [comment]
pkl文件的打印结果中没有看到模型权重矩阵，只能看到网络结构，我之前复现的其他权重（tar后缀）和网上搜索到的pkl文件的txt解析都是只有参数矩阵，并且以字典形式存在，请问这是正常的吗？改如何读取pkl文件内的参数呢？








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Renke ***@***.***&gt;; 
发送时间: 2024年4月1日(星期一) 上午9:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kourenke/LW-IRSTNet] pkl模型如何使用 (Issue #2)














 
pkl文件仅包含模型参数，需要把网络模型放到同一路径
